server:
  port: 8080

spring:
  application:
    name: member-service

eureka:
  instance:
    instance-id: member-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka