server:
  port: 9090

refresh-test:
  word: hi

eureka:
  instance:
    instance-id: book-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
  endpoint:
    refresh:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.service.book:
      client: DEBUG

  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"