server:
  port: 9090

spring:
  application:
    name: book-service

eureka:
  instance:
    instance-id: book-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka