server:
  port: 8000

refresh-test:
  word: hi

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: member-service
            uri: lb://MEMBER-SERVICE
            predicates:
              - Path=/api/{version}/members/**

          - id: book-service
            uri: lb://BOOK-SERVICE
            predicates:
              - Path=/api/{version}/books/**

eureka:
  instance:
    instance-id: gateway-service-instance

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
  endpoint:
    refresh:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org.springframework.cloud:
      gateway: TRACE

  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
